name: Security Scan

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
      - master

jobs:
  security:
    uses: fasttrack-solutions/ci/.github/workflows/golang-security.yml@main
    with:
      go-version: "~1.22"
    secrets: inherit
