name: Security Scan
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    uses: fasttrack-solutions/ci/.github/workflows/golang-security.yml@main
    with:
      go-version: "~1.23"
    secrets: inherit
